# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'resiShare' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for resiShare
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Messaging'

  target 'resiShareTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'resiShare-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for resiShare-tvOS

  target 'resiShare-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
